In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
X = np.array([[0,0,0],                       # Features
         [0,0,1],
         [0,1,0],
         [0,1,1],
         [1,0,0],
         [1,0,1],
         [1,1,0],
         [1,1,1]]
        )

ya = np.array([0,1,0,0,1,1,0,1]).reshape(8,1)     # Output

In [3]:
X.shape,ya.shape

((8, 3), (8, 1))

In [4]:
def sigmoid(a):
    return 1/(1+np.exp(-a))

In [5]:
sigmoid(0),sigmoid(-10),sigmoid(10)

(0.5, 4.5397868702434395e-05, 0.9999546021312976)

In [10]:
W = np.random.rand(3,1)
for i in range(10):
    yp = sigmoid(np.dot(X,W))
    dw = 2*np.dot(X.T,(yp-ya))
    W = W - 0.1 * dw  # learning rate = 0.1


In [11]:
W

array([[ 1.19835776],
       [-1.75023639],
       [ 1.19016416]])

In [12]:
np.round(sigmoid(np.dot(X,W)))

array([[0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.]])

In [13]:
np.random.rand(3,1)

array([[0.04727685],
       [0.37487899],
       [0.1001553 ]])